name = "trmnl-oauth-proxy"
main = "src/index.js"
compatibility_date = "2024-03-21"

kv_namespaces = [
  { binding = "AUTH_KV", id = "local" }
]

# Workflow configuration
[[workflows]]
name = "token-refresh"
binding = "TOKEN_REFRESH_WORKFLOW"

# Cron trigger configuration
[triggers]
crons = ["0 */2 * * *"]  # Run every 2 hours 